version: '3.8'

services:
  web:
    build:
        context: .
        dockerfile: Docker/development/Dockerfile
    command: bash ./scripts/start.sh
    ports:
        - "8000:8000"
    volumes:
        - .:/app