version: '3.8'


services:
  api:
    build:
        context: .
        dockerfile: Docker/development/Dockerfile
    command: bash ./scripts/start.sh
    env_file: 
        - "Docker/development/env/public"
        - "Docker/development/env/private"
    ports:
        - "8000:8000"
    volumes:
        - .:/app
    depends_on: 
        - db

  db:
    image: postgres:11
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=football
        - POSTGRES_PASSWORD=data
        - POSTGRES_DB=football_data_db
    volumes:
        - ./postgres-data:/var/lib/postgresql/data