"""remove team column from players

Revision ID: edb0be9d8fe4
Revises: 3bb194006146
Create Date: 2020-10-15 01:38:53.366127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb0be9d8fe4'
down_revision = '3bb194006146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('players_team_fkey', 'players', type_='foreignkey')
    op.drop_column('players', 'team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('team', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('players_team_fkey', 'players', 'teams', ['team'], ['id'])
    # ### end Alembic commands ###
